version: '2'
services:
    master:
        volumes: 
            - ./logs:/usr/local/spark/logs:rw
        image: "spark"
        hostname: master
        command: 
            - "/usr/local/spark/sbin/start-all.sh"
            - "&&"
            - "/usr/sbin/sshd"
            - "-D"
        tty: true
    slave1:
        volumes: 
            - ./logs:/usr/local/spark/logs:rw
        image: "spark"
        hostname: slave1
        tty: true
        links:
            - master
    slave2:
        volumes: 
            - ./logs:/usr/local/spark/logs:rw
        image: "spark"
        hostname: slave2
        tty: true
        links:
            - master
