version: '2'
services:
    namenode:
        image: shivakrishnaah/hadoop:2.7.3
        hostname: namenode
        container_name: namenode
        volumes: 
             - /Users/peel/Downloads/hadoop-2.7.3/etc/hadoop:/usr/local/hadoop-2.7.3/etc/hadoop:rw
             - .:/usr/local/shell:ro
        env_file: ./environment.env
        entrypoint: ["/usr/local/command_runner.sh","/usr/local/shell/namenode-services.sh"]
        #tty: true
        ports:
            - "50070:50070"
            - "8088:8088"
            - "8020:8020"
            - "19888:19888"
        networks:
            main:
                aliases:
                    - namenode
    datanode:
        image: shivakrishnaah/hadoop:2.7.3
        links: 
            - namenode
        volumes: 
             - /Users/peel/Downloads/hadoop-2.7.3/etc/hadoop:/usr/local/hadoop-2.7.3/etc/hadoop:rw
             - .:/usr/local/shell:ro
        env_file: ./environment.env
        entrypoint: ["/usr/local/command_runner.sh","/usr/local/shell/datanode-services.sh"]
        #tty: true
        networks:
            - main
networks: 
    main:
        driver: bridge

